apiVersion: v1
kind: Secret
metadata:
  name: packbuilder-config
type: Opaque
stringData:
  ConnectionStrings__Redis: "valkey-service:6379"
  AppSettings__FrontendBaseUrl: "https://packbuilder.org"
  AppSettings__BackendBaseUrl: "https://api.packbuilder.org"
  # AppSettings__BackendBaseUrl: "http://localhost:5013" use for non deployment builds
  # AppSettings__FrontendBaseUrl: "http://localhost:3000" use for non deployment builds
  DB__ConnectionString: "Host=postgres-service;Port=5432;Database=packbuilder;Username=postgres;Password=password"
  Curseforge__BaseUrl: "https://api.curseforge.com"
  Brevo__BaseUrl: "https://api.brevo.com/v3/"
  Curseforge__ApiKey: ""
  Brevo__ApiKey: ""
  Jwt__key: ""